spring:
  datasource:
    url: jdbc:postgresql://postgres:5432/transactions
    username: transaction_app
    password: transaction_app
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
  kafka:
    bootstrap-servers: kafka:9092

app:
  messaging:
    kafka:
      enabled: true
